name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**\build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build
        run: chmod +x ./gradlew && ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: jar
          path: build/libs
